apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart4.fullname" . }}
  labels:
    {{- include "chart4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      name: mysql
      nodePort: 32100
  selector:
    {{- include "chart4.selectorLabels" . | nindent 4 }}
