apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart5.fullname" . }}
  labels:
    {{- include "chart5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      name: mysql
  selector:
    {{- include "chart5.selectorLabels" . | nindent 4 }}
